In [1]:
from dipy.core.geometry import rodrigues_axis_rotation
import numpy as np

In [7]:
theta = 90

In [19]:
theta_x = 45
theta_y = 10
theta_z = 10

In [22]:
rot0 = rodrigues_axis_rotation(np.array([1, 0, 0]), theta_x)
rot1 = rodrigues_axis_rotation(np.array([0, 1, 0]), theta_y)
rot2 = rodrigues_axis_rotation(np.array([0, 0, 1]), theta_z)

In [23]:
R = rot0 @ rot1 @ rot2

In [31]:
v = np.array([1, 1, 1])
v = v / np.sqrt(np.dot(v, v))

In [35]:
vv = R @ np.eye(3)

In [36]:
np.dot(vv, vv)

array([[ 0.8992489 , -0.15666764,  0.40841972],
       [ 0.39957711, -0.08576565, -0.91267869],
       [ 0.1780156 ,  0.98392048, -0.01452387]])

In [40]:
np.dot(vv[2], vv[2])

0.9999999999999999

In [41]:
mevals = np.array([[0.001, 0.0005, 0.0005], 
                   [0.1, 0.01, 0.01]])

angles = [(90, 0), (90, 0)]

In [42]:
from dipy.sims.voxel import multi_tensor

/srv/conda/envs/notebook/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/srv/conda/envs/notebook/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/srv/conda/envs/notebook/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/srv/conda/envs/notebook/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [48]:
perfusion_fraction = 0

In [49]:
from dipy.core.gradients import gradient_table

In [50]:
gtab = gradient_table('./data/DWI_IVIM6.bval', './data/DWI_IVIM6.bvec', b0_threshold=0)

In [52]:
sim = multi_tensor(gtab, mevals=mevals, snr=1000, fractions=[100 * (1-perfusion_fraction), 
                                                             perfusion_fraction * 100])[0]

In [53]:
from dipy.reconst.dti import TensorModel

In [54]:
dtm = TensorModel(gtab)

In [55]:
dtf = dtm.fit(sim)

In [73]:
dtf.evecs, dtf.evals

(array([[ 1.31014592e-03, -5.71978957e-01,  8.20267247e-01],
        [-1.38367506e-03,  8.20266128e-01,  5.71980388e-01],
        [ 9.99998184e-01,  1.88436110e-03, -2.83235300e-04]]),
 array([0.00100034, 0.00050145, 0.00049858]))

In [71]:
from dipy.core.geometry import cart2sphere, sphere2cart

theta0, phi0 = cart2sphere(* dtf.evecs[0])[1:]
theta1, phi1 = cart2sphere(* dtf.evecs[1])[1:]
theta2, phi2 = cart2sphere(* dtf.evecs[2])[1:]



In [76]:
evecs = np.vstack([np.array(sphere2cart(1, theta0, phi0)),
                   np.array(sphere2cart(1, theta1, phi1)),
                   np.array(sphere2cart(1, theta2, phi2))])


In [77]:
evecs

array([[ 1.31014592e-03, -5.71978957e-01,  8.20267247e-01],
       [-1.38367506e-03,  8.20266128e-01,  5.71980388e-01],
       [ 9.99998184e-01,  1.88436110e-03, -2.83235300e-04]])

In [78]:
np.allclose(evecs, dtf.evecs)

True